#!/bin/bash

INTERACTIVE=True
ASK_TO_REBOOT=0

USER=${SUDO_USER:-$(who -m | awk '{ print $1 }')}

APP_NAME="Beepy Config"
TITLE="$APP_NAME Setup"

CONFIG_DIR="$HOME/.config/beepy-config"
SCRIPTS_DIR="$CONFIG_DIR/scripts"

calc_wt_size() {
  # NOTE: it's tempting to redirect stderr to /dev/null, so suppress error
  # output from tput. However in this case, tput detects neither stdout or
  # stderr is a tty and so only gives default 80, 24 values
  WT_HEIGHT=18
  WT_WIDTH=$(tput cols)

  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=80
  fi
  if [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=120
  fi

  WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

do_get_on_off_option() {
  boolean=$1

  if [ "$boolean" -eq 1 ]; then
    echo "ON"
  else
    echo "OFF"
  fi
}

do_init() {
  do_setup_bashrc_beepy "$CONFIG_DIR" || whiptail --msgbox "No .bashrc or .bash_aliases file found.\\n\\nPlease create one and run this script again." 20 60 2
}

do_finish() {
  if [ $ASK_TO_REBOOT -eq 1 ]; then
    whiptail --yesno "Would you like to reboot now?" 20 60 2
    if [ $? -eq 0 ]; then # yes
      sync
      reboot
    fi
  fi

  exit 0
}

do_hide_terminal_name() {
  do_bashrc_add_export "PS1" "\w \$ "
}

do_improve_cat() {
  sudo apt-get install -y bat

  do_bashrc_add_alias "cat" "batcat"
}

do_enable_battery_saver() {
  sh "$SCRIPTS_DIR/enable_battery_savings"
}

do_enable_zoom() {
  sh "$SCRIPTS_DIR/install_zoom"

  do_bashrc_add_alias "zi" "zoom in"
  do_bashrc_add_alias "zo" "zoom out"
  do_bashrc_add_alias "zr" "zoom"
}

do_enable_weather() {
  location=$1
  units=$2

  sh "$SCRIPTS_DIR/install_wx" "$location" "$units"

  do_bashrc_add_alias "weather" "wx"
}

do_install_fonts() {
  sh "$SCRIPTS_DIR/install_fonts"
}

do_persist_font() {
  font=$1

  sh "$SCRIPTS_DIR/persist_font" "$font"
}

do_set_font() {
  font=$1

  do_install_fonts

  sh "$SCRIPTS_DIR/set_font" "$font"

  do_persist_font_prompt "$font"
}

do_preview_all_fonts() {
  do_install_fonts

  sh "$SCRIPTS_DIR/preview_terminus_fonts"
}

do_install_reddit() {
  sudo apt-get install -y rtv

  do_bashrc_add_alias "reddit" "rtv"
}

do_install_browser() {
  package=$1
  browser_command=$2

  sudo apt-get install -y "$package"

  do_bashrc_add_alias "web" "$browser_command"
}

do_install_email_client() {
  package=$1
  email_client_command=$2

  sudo apt-get install -y "$package"

  do_bashrc_add_alias "email" "$email_client_command"
}

do_install_rss_reader() {
  package=$1
  rss_reader_command=$2

  sh "$SCRIPTS_DIR/install_rss" "$package"

  do_bashrc_add_alias "rss" "$rss_reader_command"
}

do_browser_menu() {
  CHOICE=$(whiptail --title "$TITLE" --radiolist "Which browser would you like to use?" 15 60 4 \
      "1" "lynx" ON \
      "2" "w3m" OFF \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      # User made a selection
      case $CHOICE in
          1)
              do_install_browser "lynx" "lynx"
              ;;
          2)
              do_install_browser "w3m" "w3m"
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_apps_menu
  fi
}

do_email_client_menu() {
  CHOICE=$(whiptail --title "$TITLE" --radiolist "Which email client would you like to use?" 15 60 4 \
      "1" "neomutt" ON \
      "2" "alpine" OFF \
      "3" "aerc" OFF \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      # User made a selection
      case $CHOICE in
          1)
              do_install_email_client "neomutt" "neomutt"
              ;;
          2)

              do_install_email_client "alpine" "alpine"
              ;;
          3)
              do_install_email_client "aerc" "aerc"
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_apps_menu
  fi
}

do_rss_populate_prompt() {
  reader=$1

  if (whiptail --title "$TITLE" --yesno "Would you like to populate $reader with some common news feeds?" 15 60 4 \
      3>&1 1>&2 2>&3); then
    bash "$SCRIPTS_DIR/populate_rss_reader" "$reader" # This NEEDs to run as bash, not sh
  fi
}

do_rss_reader_menu() {
  CHOICE=$(whiptail --title "$TITLE" --radiolist "Which RSS reader would you like to use?" 15 60 4 \
      "1" "newsboat" ON \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      # User made a selection
      case $CHOICE in
          1)
              do_install_rss_reader "newsboat" "newsboat"
              do_rss_populate_prompt "newsboat"
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_apps_menu
  fi
}

do_weather_menu() {
  LOCATION=$(whiptail --title "$TITLE" --inputbox "What is your location (nearest city)?" 15 60 3>&1 1>&2 2>&3)
  # Replace spaces with + in location
  LOCATION=${LOCATION// /+}

  CHOICE=$(whiptail --title "$TITLE" --radiolist "Which units would you like to use?" 15 60 4 \
            "1" "imperial" ON \
            "2" "metric" OFF \
            3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      case $CHOICE in
          1)
              do_enable_weather "$LOCATION" "imperial"
              ;;
          2)
              do_enable_weather "$LOCATION" "metric"
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_apps_menu
  fi
}

do_password_manager_menu() {
  NAME=$(whiptail --title "$TITLE" --inputbox "What is your name?" 15 60 3>&1 1>&2 2>&3)

  EMAIL_ADDRESS=$(whiptail --title "$TITLE" --inputbox "What is your email address?" 15 60 3>&1 1>&2 2>&3)

  sh "$SCRIPTS_DIR/init_password_store" "$NAME" "$EMAIL_ADDRESS"
}

do_apps_menu() {
  CHOICE=$(whiptail --title "$TITLE" --menu "What would you like to do?" 15 60 4 \
      "1" "Set browser" \
      "2" "Set email client" \
      "3" "Set RSS reader" \
      "4" "Set weather" \
      "5" "Install Reddit" \
      "6" "Set up password manager" \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      case $CHOICE in
          1)
              do_browser_menu
              ;;
          2)
              do_email_client_menu
              ;;
          3)
              do_rss_reader_menu
              ;;
          4)
              do_weather_menu
              ;;
          5)
              do_install_reddit
              ;;
          6)
              do_password_manager_menu
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_main_menu
  fi
}

do_persist_font_prompt() {
  font=$1
  if (whiptail --title "$TITLE" --yesno "Would you like to keep this font?" 15 60 4 \
      3>&1 1>&2 2>&3); then
    do_persist_font "$font"
  fi
}

do_fonts_selection_menu() {
  CHOICE=$(whiptail --title "$TITLE" --radiolist "Which font size would you like to use?" 15 60 4 \
          "1" "12 regular" \
          "2" "12 bold" \
          "3" "14 regular" \
          "4" "14 bold" \
          "5" "16 regular" \
          "6" "16 bold" \
          "7" "18 regular" \
          "8" "18 bold" \
          "9" "20 regular" \
          "10" "20 bold" \
          "11" "22 regular" \
          "12" "22 bold" \
          "13" "24 regular" \
          "14" "24 bold" \
          "15" "28 regular" \
          "16" "28 bold" \
          "17" "32 regular" \
          "18" "32 bold" \
          3>&1 1>&2 2>&3)

      if [ $? -eq 0 ]; then
          case $CHOICE in
              1)
                  do_set_font "ter-powerline-v12n.psf.gz"
                  ;;
              2)
                  do_set_font "ter-powerline-v12b.psf.gz"
                  ;;
              3)
                  do_set_font "ter-powerline-v14n.psf.gz"
                  ;;
              4)
                  do_set_font "ter-powerline-v14b.psf.gz"
                  ;;
              5)
                  do_set_font "ter-powerline-v16n.psf.gz"
                  ;;
              6)
                  do_set_font "ter-powerline-v16b.psf.gz"
                  ;;
              7)
                  do_set_font "ter-powerline-v18n.psf.gz"
                  ;;
              8)
                  do_set_font "ter-powerline-v18b.psf.gz"
                  ;;
              9)
                  do_set_font "ter-powerline-v20n.psf.gz"
                  ;;
              10)
                  do_set_font "ter-powerline-v20b.psf.gz"
                  ;;
              11)
                  do_set_font "ter-powerline-v22n.psf.gz"
                  ;;
              12)
                  do_set_font "ter-powerline-v22b.psf.gz"
                  ;;
              13)
                  do_set_font "ter-powerline-v24n.psf.gz"
                  ;;
              14)
                  do_set_font "ter-powerline-v24b.psf.gz"
                  ;;
              15)
                  do_set_font "ter-powerline-v28n.psf.gz"
                  ;;
              16)
                  do_set_font "ter-powerline-v28b.psf.gz"
                  ;;
              17)
                  do_set_font "ter-powerline-v32n.psf.gz"
                  ;;
              18)
                  do_set_font "ter-powerline-v32b.psf.gz"
                  ;;
              *)
                  # This should never happen
                  whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
                  ;;
          esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
      else
          do_fonts_main_menu
      fi
}

do_fonts_main_menu() {
  CHOICE=$(whiptail --title "$TITLE" --menu "What would you like to do?" 15 60 4 \
      "1" "Select font size" \
      "2" "Preview all fonts" \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      # User made a selection
      case $CHOICE in
          1)
              do_fonts_selection_menu
              ;;
          2)
              do_preview_all_fonts
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_display_menu
  fi
}


do_display_extras_menu() {
  CHOICE=$(whiptail --title "$TITLE" --menu \
    "What would you like to configure?" 15 60 4 \
    "1" "Hide computer name to save space" \
    "2" "Enable zoom" \
    "3" "Invert colors" \
    3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
          case $CHOICE in
              1)
                  do_hide_terminal_name
                  ;;
              2)
                  do_enable_zoom
                  ;;
              3)
                  do_bashrc_invert_colors
                  ;;
              *)
                  # This should never happen
                  whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
                  ;;
          esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
    do_display_menu
  fi
}

do_display_menu() {
  CHOICE=$(whiptail --title "$TITLE" --menu "What would you like to configure?" 15 60 4 \
        "1" "Fonts" \
        "2" "Extras" \
        3>&1 1>&2 2>&3)

    if [ $? -eq 0 ]; then
        case $CHOICE in
            1)
                do_fonts_main_menu
                ;;
            2)
                do_display_extras_menu
                ;;
            *)
                # This should never happen
                whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
                ;;
        esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
    else
        do_main_menu
    fi
}

do_keyboard_remap_beepy_button_menu() {
  source "$SCRIPTS_DIR/keyboard"

  CHOICE=$(whiptail --title "$TITLE" --radiolist "Which key would you like the Beepy button to simulate?" 15 60 4 \
      "1" "tmux command" ON \
      "2" "Esc" OFF \
      "3" "q" OFF \
      "4" "Tab" OFF \
      "5" "Vim command" OFF \
      "6" "Cut" OFF \
      "7" "Copy" OFF \
      "8" "Paste" OFF \
      "9" "Where am I?" OFF \
      "10" "List files" OFF \
      "11" "Log out" OFF \
      "12" "Exit" OFF \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      case $CHOICE in
          1)
              do_remap_beepy_button "Control_b"
              ;;
          2)
              do_remap_beepy_button "Escape"
              ;;
          3)
              do_remap_beepy_button "q"
              ;;
          4)
              do_remap_beepy_button "Tab"
              ;;
          5)
              do_remap_beepy_button "Meta_colon"
              ;;
          6)
              do_remap_beepy_button "F31"
              ;;
          7)
              do_remap_beepy_button "F30"
              ;;
          8)
              do_remap_beepy_button "F32"
              ;;
          9)
              do_remap_beepy_button "F44"
              ;;
          10)
              do_remap_beepy_button "F46"
              ;;
          11)
              do_remap_beepy_button "Incr_Console"
              ;;
          12)
              do_remap_beepy_button "F45"
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_keyboard_menu
  fi
}

do_keyboard_menu() {
  source "$SCRIPTS_DIR/beepy_ppa"

  if ! do_check_if_beepy_ppa_is_installed; then
    whiptail --msgbox "Please enable the Beepy PPA first." 20 60 1
    do_beepy_ppa_menu
  fi

  CHOICE=$(whiptail --title "$TITLE" --menu "What would you like to do?" 15 60 4 \
      "1" "Remap Beepy button" \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      case $CHOICE in
          1)
              do_keyboard_remap_beepy_button_menu
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_main_menu
  fi
}

do_tmux_status_bar_location_menu() {
  CHOICE=$(whiptail --title "$TITLE" --radiolist "Where would you like to display the status bar?" 15 60 4 \
      "1" "Top" ON \
      "2" "Bottom" OFF \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      case $CHOICE in
          1)
              do_tmux_move_status_bar "top"
              ;;
          2)
              do_tmux_move_status_bar "bottom"
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_customize_tmux_menu
  fi
}

do_tmux_change_status_update_interval_menu() {
  INTERVAL=$(whiptail --title "$TITLE" --inputbox "How often would you like to update the status bar (in seconds)?" 15 60 3>&1 1>&2 2>&3)

  do_tmux_set_update_interval "$INTERVAL"
}

do_customize_tmux_menu() {
  source "$SCRIPTS_DIR/edit_tmux_conf"

  CHOICE=$(whiptail --title "$TITLE" --menu "What would you like to do?" 15 60 4 \
        "1" "Display battery and WiFi strength" \
        "2" "Display date" \
        "3" "Move status bar" \
        "4" "Change status update interval" \
        3>&1 1>&2 2>&3)

    if [ $? -eq 0 ]; then
        case $CHOICE in
            1)
                do_tmux_add_levels_to_status_bar
                ;;
            2)
                do_tmux_add_date_to_status_bar
                ;;
            3)
                do_tmux_status_bar_location_menu
                ;;
            4)
                do_tmux_change_status_update_interval_menu
                ;;
            *)
                # This should never happen
                whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
                ;;
        esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
    else
        do_extras_menu
    fi
}

do_extras_menu() {
  CHOICE=$(whiptail --title "$TITLE" --menu "What would you like to do?" 15 60 4 \
      "1" "Improve cat" \
      "2" "Customize tmux" \
      "3" "Save battery" \
      3>&1 1>&2 2>&3)

  if [ $? -eq 0 ]; then
      case $CHOICE in
          1)
              do_improve_cat
              ;;
          2)
              do_customize_tmux_menu
              ;;
          3)
              do_enable_battery_saver
              ;;
          *)
              # This should never happen
              whiptail --msgbox "Programmer error: unrecognized option" 20 60 1
              ;;
      esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
  else
      do_main_menu
  fi
}

do_main_menu() {
  CHOICE=$(whiptail --title "$TITLE" --menu "Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
          "Display" "Configure display" \
          "Keyboard" "Configure keyboard" \
          "Apps" "Configure apps" \
          "Extras" "Configure extras" \
          3>&1 1>&2 2>&3)
      RET=$?
      if [ $RET -eq 1 ]; then
        do_finish
      elif [ $RET -eq 0 ]; then
        case "$CHOICE" in
          "Display") do_display_menu ;;
          "Keyboard") do_keyboard_menu ;;
          "Apps") do_apps_menu ;;
          "Extras") do_extras_menu ;;
          *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
        esac || whiptail --msgbox "There was an error running option $CHOICE" 20 60 1
      else
        exit 1
      fi
}

#
# Interactive use loop
#
if [ "$INTERACTIVE" = True ]; then
  source "$SCRIPTS_DIR/edit_bashrc_beepy"

  calc_wt_size
  do_init
  while [ "$USER" = "root" ] || [ -z "$USER" ]; do
    if ! USER=$(whiptail --inputbox "$APP_NAME could not determine the default user.\\n\\nWhat user should these settings apply to?" 20 60 pi 3>&1 1>&2 2>&3); then
      return 0
    fi
  done
  while true; do
    do_main_menu
  done
fi
