#!/bin/bash

TMUX_CONFIG_FILE="$HOME/.tmux.conf"

do_ensure_tmux_conf_exists() {
    if [ ! -f "$TMUX_CONFIG_FILE" ]; then
        touch "$TMUX_CONFIG_FILE"
    fi
}

do_tmux_add_line() {
  line=$1

  do_tmux_remove_line "$line"

  echo "$line" >> "$TMUX_CONFIG_FILE"
}

do_tmux_remove_line() {
  line=$1

  # Remove line if found
  if grep -q "$line" "$TMUX_CONFIG_FILE"; then
    sed -i "/$line/d" "$TMUX_CONFIG_FILE"
  fi
}

do_tmux_remove_line_by_regex_pattern() {
  pattern=$1

  # Remove line if found
  if grep -q "$pattern" "$TMUX_CONFIG_FILE"; then
    sed -i "/$pattern/d" "$TMUX_CONFIG_FILE"
  fi
}

do_tmux_add_levels_to_status_bar() {
  do_ensure_tmux_conf_exists

  do_tmux_add_line "set -g status-right '#(sh $SCRIPTS_DIR/wifi_strength) #(sh $SCRIPTS_DIR/battery_level)'"
}

do_tmux_add_date_to_status_bar() {
  do_ensure_tmux_conf_exists

  do_tmux_add_line "set -g status-left \"#(date +'%I:%M%p') \""
}

do_tmux_move_status_bar() {
  do_ensure_tmux_conf_exists

  position=$1

  do_tmux_remove_line_by_regex_pattern "set -g status-position [a-z]+"

  do_tmux_add_line "set -g status-position $position"
}

do_tmux_set_update_interval() {
  do_ensure_tmux_conf_exists

  interval=$1

  do_tmux_remove_line_by_regex_pattern "set -g status-interval [0-9]+"

  do_tmux_add_line "set -g status-interval $interval"
}
