#!/bin/bash

BEEPY_BASHRC_TEMPLATE_PATH=".bashrc.beepy"
BEEPY_BASHRC_FILE=""

do_confirm_bashrc_exists() {
  # Check that a .bashrc or .bash_aliases file exists
  if [ -f "$HOME"/.bash_aliases ]
  then
      BASHRC_FILE="$HOME"/.bash_aliases
  elif [ -f "$HOME"/.bashrc ]
  then
      BASHRC_FILE="$HOME"/.bashrc
  else
      BASHRC_FILE=''
  fi

  # if .bashrc or .bash_aliases does not exist, exit
  if [[ ! $BASHRC_FILE ]]
  then
      exit 1
  fi
}

do_setup_bashrc_beepy() {
  do_confirm_bashrc_exists || exit 1

  dest_path=$1

  BEEPY_BASHRC_FILE="$dest_path/$BEEPY_BASHRC_TEMPLATE_PATH"

  # Copy base dotfile for modification
  cp "$BEEPY_BASHRC_TEMPLATE_PATH" "$BEEPY_BASHRC_FILE"

  # Add dotfile to .bashrc
  INCLUDE_BASHRC_SOURCE="[[ -s \"$BEEPY_BASHRC_FILE_DEST\" ]] && source $BEEPY_BASHRC_FILE_DEST"
  ALREADY_EXISTS=$(tail -n 1 "$BASHRC_FILE")
  if [ "$ALREADY_EXISTS" == "$INCLUDE_BASHRC_SOURCE" ]
  then
      echo ""
  else
      echo "$INCLUDE_BASHRC_SOURCE" >> "$BASHRC_FILE"
  fi
}

do_bashrc_find_existing_alias() {
  key=$1

  # Return 1 if found, 0 if not found
  grep -F "alias $key" "$BEEPY_BASHRC_FILE"

  return $?
}

do_bashrc_find_existing_export() {
  key=$1

  # Return 1 if found, 0 if not found
  grep -F "export $key" "$BEEPY_BASHRC_FILE"

  return $?
}

do_bashrc_add_alias() {
  key=$1
  value=$2

  do_bashrc_remove_alias "$key"

  echo "alias $key='$value'" >> "$BEEPY_BASHRC_FILE"
}

do_bashrc_remove_alias() {
  key=$1

  # Remove alias if found
  if do_bashrc_find_existing_alias "$key"; then
    sed -i "/alias $key/d" "$BEEPY_BASHRC_FILE"
  fi
}

do_bashrc_add_export() {
  key=$1
  value=$2

  do_bashrc_remove_export "$key"

  echo "export $key='$value'" >> "$BEEPY_BASHRC_FILE"
}

do_bashrc_remove_export() {
  key=$1

  # Remove export if found
  if do_bashrc_find_existing_export "$key"; then
    sed -i "/export $key/d" "$BEEPY_BASHRC_FILE"
  fi
}

do_bashrc_add_line() {
  line=$1

  do_bashrc_remove_line "$line"

  echo "$line" >> "$BEEPY_BASHRC_FILE"
}

do_bashrc_remove_line() {
  line=$1

  # Remove line if found
  if grep -q "$line" "$BEEPY_BASHRC_FILE"; then
    sed -i "/$line/d" "$BEEPY_BASHRC_FILE"
  fi
}

do_bashrc_remove_line_by_regex_pattern() {
  pattern=$1

  # Remove line if found
  if grep -q "$pattern" "$BEEPY_BASHRC_FILE"; then
    sed -i "/$pattern/d" "$BEEPY_BASHRC_FILE"
  fi
}

do_bashrc_invert_colors() {
  do_bashrc_remove_line_by_regex_pattern " > \/dev\/tty1$"

  echo "echo -e '\033[?5l' > /dev/tty1" >> "$BEEPY_BASHRC_FILE"
}
