#!/bin/bash

TMUX_CONFIG_FILE="$HOME/.tmux.conf"

do_ensure_tmux_conf_exists() {
    if [ ! -f "$TMUX_CONFIG_FILE" ]; then
        touch "$TMUX_CONFIG_FILE"
    fi
}

do_tmux_add_levels_to_status_bar() {
  do_ensure_tmux_conf_exists

  echo "set -g status-right '#(sh $SCRIPTS_DIR/wifi_strength) #(sh $SCRIPTS_DIR/battery_level)'" >> "$TMUX_CONFIG_FILE"
}

do_tmux_add_date_to_status_bar() {
  do_ensure_tmux_conf_exists

  echo "set -g status-left \"#(date +'%I:%M%p') \"" >> "$TMUX_CONFIG_FILE"
}

do_tmux_move_status_bar() {
  do_ensure_tmux_conf_exists

  position=$1

  echo "set -g status-position $position" >> "$TMUX_CONFIG_FILE"
}
