#!/bin/bash

# Disable HDMI
# sudo /usr/bin/tvservice -o
# echo "/usr/bin/tvservice -o" >> /etc/rc.local

# Disable ACT led
echo 0 | sudo tee /sys/class/leds/ACT/brightness
echo none | sudo tee /sys/class/leds/ACT/trigger
echo "echo 0 | sudo tee /sys/class/leds/ACT/brightness" >> /etc/rc.local
echo "echo none | sudo tee /sys/class/leds/ACT/trigger" >> /etc/rc.local
