#!/bin/bash

# Ref: https://ardangelo.github.io/beepy-ppa/#adding-to-apt-and-installing-drivers
curl -s --compressed "https://ardangelo.github.io/beepy-ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/beepy.gpg >/dev/null || true
sudo curl -s --compressed -o /etc/apt/sources.list.d/beepy.list "https://ardangelo.github.io/beepy-ppa/beepy.list"
sudo apt-get -y install beepy-kbd sharp-drm
