#!/bin/bash

name=$1
email_address=$2

# Set up password store if not already set up
  sudo apt-get install pass git
  if [ ! -d "$HOME"/.password-store ]
  then
      # Generate GPG key
      gpg --full-gen-key --batch <(echo "Key-Type: 1"; \
                                       echo "Key-Length: 4096"; \
                                       echo "Subkey-Type: 1"; \
                                       echo "Subkey-Length: 4096"; \
                                       echo "Expire-Date: 0"; \
                                       echo "Name-Real: $name"; \
                                       echo "Name-Email: $email_address"; \
                                       echo "%no-protection"; )

      # Get the Key ID of the key we just generated
      KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep -E "^sec" | tail -n 1 | awk '{print $2}' | awk -F'/' '{print $2}')

      # Initialize password store
      pass init "$KEY_ID"

      # Set up git config for password store
      pass git init
      cd "$HOME"/.password-store/.git || exit
      git config user.name "$name"
      git config user.email "$email_address"
  fi
