#!/bin/bash

# Enable the beepy-ppa
curl -s --compressed "https://ardangelo.github.io/beepy-ppa/KEY.gpg" | gpg --dearmor | sudo tee "$PPA_GPG" >/dev/null || true
sudo curl -s --compressed -o "$PPA_LIST" "https://ardangelo.github.io/beepy-ppa/beepy.list"

# Remove any existing beepy drivers
sudo rm /lib/modules/*/extra/bbqX0kbd.ko* || true
sudo rm /lib/modules/*/extra/sharp-drm.ko* || true
sudo rm /boot/overlays/i2c-bbqX0kbd.dtbo || true
sudo rm /boot/overlays/sharp.dtbo || true
sudo depmod -a

# Remove any existing beepy drivers from /etc/modules and /boot/config.txt
sudo sed -i 's/^\(dtoverlay=bbqX0kbd\)/#\1/' /boot/config.txt || true
sudo sed -i 's/^\(dtoverlay=sharp\)/#\1/' /boot/config.txt || true
sudo sed -i 's/bbqX0kbd/#bbqX0kbd/' /etc/modules || true
sudo sed -i 's/sharp/#sharp/' /etc/modules || true

# Install the beepy drivers
sudo apt-get -y install beepy-kbd sharp-drm

# Reboot
sudo shutdown -r now
