#!/bin/bash

CONFIG_DIR="$HOME/.config/beepy-config"
REPOS_DIR="$CONFIG_DIR/repos"
SCRIPTS_DIR="$CONFIG_DIR/scripts"

PPA_LIST="/etc/apt/sources.list.d/beepy.list"
PPA_GPG="/etc/apt/trusted.gpg.d/beepy.gpg"

KEYMAP_FILE="/usr/share/kbd/keymaps"

# Directories for config files and git repos
mkdir -p "$CONFIG_DIR" || true
mkdir -p "$REPOS_DIR" || true
mkdir -p "$SCRIPTS_DIR" || true

# Copy the keymap to the keymap directory
sudo curl -o "$KEYMAP_FILE" "https://raw.githubusercontent.com/nwithan8/beepy-config/master/configs/beepy-kbd.map"

# Sync files
sync
