#!/bin/bash

CONFIG_DIR="$HOME/.config/beepy-config"
REPOS_DIR="$CONFIG_DIR/repos"
SCRIPTS_DIR="$CONFIG_DIR/scripts"

PPA_LIST="/etc/apt/sources.list.d/beepy.list"
PPA_GPG="/etc/apt/trusted.gpg.d/beepy.gpg"

KEYMAP_DIR="/usr/share/kbd/keymaps"

# Enable the beepy-ppa
curl -s --compressed "https://ardangelo.github.io/beepy-ppa/KEY.gpg" | gpg --dearmor | sudo tee "$PPA_GPG" >/dev/null || true
sudo curl -s --compressed -o "$PPA_LIST" "https://ardangelo.github.io/beepy-ppa/beepy.list"
sudo apt-get -y install beepy-kbd sharp-drm

# Update package lists
sudo apt update

# Directories for config files and git repos
mkdir -p "$CONFIG_DIR" || true
mkdir -p "$REPOS_DIR" || true
mkdir -p "$SCRIPTS_DIR" || true

# Make all scripts executable
chmod +x scripts/*

# Copy all scripts to the scripts directory
cp -r scripts/* "$SCRIPTS_DIR"

# Copy the keymap to the keymap directory
sudo cp configs/beepy-kbd.map "$KEYMAP_DIR"

# Sync files
sync
