#!/bin/bash

for font in /usr/share/consolefonts/ter-powerline-v*;
  do
    font_name=$(echo "$font" | sed -e 's/\/usr\/share\/consolefonts\/ter-powerline-v\([0-9]*\)\(n\|b\).psf.gz/\1 \2/')
    sudo setfont $font;
    sleep 3;
    echo "| $font_name | `tput cols`x`tput lines` |";
    sleep 1;
  done